INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILEM, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('STAFF', 'STAFF', 'IRS', '普通员工', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILEM, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('PL', 'PROJECT LEADER', 'IRS', '项目主管', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILEM, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('PM', 'PROJECT MANAGER', 'IRS', '项目经理', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILEM, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('DEPTMGR', 'DEPARTMENT MANAGER', 'IRS', '部门经理', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILEM, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('HR', 'HUMAN RESOURCE', 'IRS', '人事员', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILEM, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('HRMGR', 'HR MANAGER', 'IRS', '人事经理', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILEM, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('OUTSTAFF', 'Outsourcing Satff', 'OSS', '外包员工', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
