INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'B', 'Buddhist', '佛教', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'C', 'Christian', '基督教', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'F', 'Free Thinker', '无', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'H', 'Hindu', '印度教', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'S', 'Sikh', '锡克教', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'T', 'Taoist', '道教', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'M', 'Muslim', '伊斯兰教', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'O', 'Others', '其他', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (CODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.religion', 'U', 'Unknown', '未知', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');