INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.error.mandatory', '00', 'mandatory', '字段不能为空', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');