INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ST', 'SAO TOMEAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SV', 'SALVADORAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SW', 'KITTIAN & NEVISIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SY', 'SYRIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SZ', 'SWAZI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TD', 'CHADIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TG', 'TOGOLESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TH', 'THAI', '泰国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TI', 'TAJIKISTANI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TM', 'TURKMEN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TN', 'TUNISIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TO', 'TONGAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TP', 'EAST TIMORESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TR', 'TURK', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TT', 'TRINIDADIAN & TOBAGONIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(),
        'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TV', 'TUVALU', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TW', 'CHINESE/TAIWANESE', '中国台湾', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'TZ', 'TANZANIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'UG', 'UGANDAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'UK', 'BRITISH SUBJECT', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'UR', 'UKRAINIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'US', 'AMERICAN', '美国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'UY', 'URUGUAYAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'UZ', 'UZBEKISTAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'VA', 'VATICAN CITY STATE (HOLY SEE)', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(),
        'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'VC', 'ST. VINCENTIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'VE', 'VENEZUELAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'VN', 'VIETNAMESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'VU', 'NI-VANUATU', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'WS', 'SAMOAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'YM', 'YEMENI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ZA', 'SOUTH AFRICAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ZM', 'ZAMBIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ZW', 'ZIMBABWEAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AD', 'ANDORRAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AE', 'UNITED ARAB EMIRATES', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AF', 'AFGHAN', '阿富汗', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AG', 'ANTIGUAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AL', 'ALBANIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AM', 'ARMENIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AO', 'ANGOLAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AR', 'ARGENTINIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AT', 'AUSTRIAN', '奥地利', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AU', 'AUSTRALIAN', '澳大利亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'AZ', 'AZERBAIJANI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BA', 'BOSNIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BB', 'BARBADOS', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BD', 'BANGLADESHI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BE', 'BELGIAN', '比利时', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BF', 'BURKINABE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BG', 'BULGARIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BH', 'BAHRAINI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BI', 'BURUNDIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BJ', 'BENINESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BL', 'BELARUSSIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BN', 'BRUNEIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BO', 'BOLIVIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BR', 'BRAZILIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BS', 'BAHAMIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BT', 'BHUTANESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BU', 'MYANMAR', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BW', 'BOTSWANA', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'BZ', 'BELIZEAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CA', 'CANADIAN', '加拿大', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CB', 'CROATIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CD', 'DEMOCRATIC REPUBLIC OF THE CONGO', '刚果（布）', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM',
        NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CF', 'CENTRAL AFRICAN REPUBLIC', '中非共和国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(),
        'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CG', 'CONGOLESE', '刚果（金）', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CH', 'SWISS', '瑞士', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CI', 'IVORY COAST', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CL', 'CHILEAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CM', 'CAMEROONIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CN', 'CHINESE', '中国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CO', 'COLOMBIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CR', 'COSTA RICAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CU', 'CUBAN', '古巴', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CV', 'CAPE VERDEAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CY', 'CYPRIOT', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'CZ', 'CZECH', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'DG', 'GERMAN', '德国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'DJ', 'DJIBOUTIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'DK', 'DANISH', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'DM', 'DOMINICAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'DO', 'DOMINICAN (REPUBLIC)', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'DZ', 'ALGERIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'EC', 'ECUADORIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'EG', 'EGYPTIAN', '埃及', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'EN', 'ESTONIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ER', 'ERITREAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ES', 'SPANISH', '西班牙', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ET', 'ETHIOPIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'FI', 'FINNISH', '芬兰', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'FJ', 'FIJIAN', '斐济', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'FR', 'FRENCH', '法国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GA', 'GABON', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GB', 'BRITISH', '英国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GC', 'BRITISH OVERSEAS TERRITORIES CITIZEN', '英国海外领土公民', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM',
        NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GD', 'GRENADIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GE', 'BRITISH OVERSEAS CITIZEN', '英国海外公民', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(),
        'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GG', 'BRITISH NATIONAL OVERSEAS', '英国（海外）', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(),
        'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GH', 'GHANAIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GJ', 'BRITISH PROTECTED PERSON', '英国（受保护人士）', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(),
        'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GM', 'GAMBIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GN', 'GUINEAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GO', 'GEORGIAN', '格鲁吉亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GQ', 'EQUATORIAL GUINEA', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GR', 'GREEK', '希腊', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GT', 'GUATEMALAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GW', 'GUINEAN (BISSAU)', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'GY', 'GUYANESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'HK', 'CHINESE/HONGKONG SAR', '中国 香港特别行政区', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'HN', 'HONDURAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'HT', 'HAITIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'HU', 'HUNGARIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ID', 'INDONESIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'IE', 'IRISH', '爱尔兰', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'IL', 'ISRAELI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'IN', 'INDIAN', '印度', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'IQ', 'IRAQI', '伊拉克', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'IR', 'IRANIAN', '伊朗', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'IS', 'ICELANDER', '冰岛', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'IT', 'ITALIAN', '意大利', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'JM', 'JAMAICAN', '牙买加', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'JO', 'JORDANIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'JP', 'JAPANESE', '日本', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KA', 'CAMBODIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KE', 'KENYAN', '肯尼亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KI', 'KIRIBATI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KM', 'COMORAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KP', '"KOREAN', '朝鲜', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KR', '"KOREAN', '韩国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KW', 'KUWAITI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KY', 'KYRGYZSTAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'KZ', 'KAZAKHSTANI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LA', 'LAOTIAN', '老挝', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LB', 'LEBANESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LC', 'ST.LUCIA', '圣卢西亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LH', 'LITHUANIAN', '立陶宛', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LI', 'LIECHTENSTEINER', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LK', 'SRI LANKAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LR', 'LIBERIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LS', 'LESOTHO', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LU', 'LUXEMBOURGER', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LV', 'LATVIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'LY', 'LIBYAN', '利比亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MA', 'MOROCCAN', '摩洛哥', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MB', 'MACEDONIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MC', 'MONACAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MD', 'MOLDAVIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MF', 'MICRONESIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MG', 'MADAGASY', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MH', 'MARSHALLESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MJ', 'MONTENEGRIN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'ML', 'MALIAN', '马里', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MN', 'MONGOLIAN', '蒙古国', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MO', 'CHINESE/MACAU SAR', '中国 澳门特别行政区', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MR', 'MAURITANEAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MT', 'MALTESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MU', 'MAURITIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MV', 'MALDIVIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MW', 'MALAWIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MX', 'MEXICAN', '墨西哥', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MY', 'MALAYSIAN', '马来西亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'MZ', 'MOZAMBICAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NA', 'NAMIBIAN', '纳米比亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NE', 'NIGER', '尼日尔', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NG', 'NIGERIAN', '尼日利亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NI', 'NICARAGUAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NO', 'NORWEGIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NP', 'NEPALESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NR', 'NAURUAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NT', 'NETHERLANDS', '荷兰', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'NZ', 'NEW ZEALANDER', '新西兰', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'OM', 'OMANI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PA', 'PANAMANIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PE', 'PERUVIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PG', 'PAPUA NEW GUINEAN', '巴布亚新几内亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PH', 'FILIPINO', '菲律宾', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PK', 'PAKISTANI', '巴基斯坦', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PL', 'POLISH', '波兰', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PN', 'PALESTINIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PT', 'PORTUGUESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PW', 'PALAUAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'PY', 'PARAGUAYAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'QA', 'QATARI', '卡塔尔', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'RF', 'RUSSIAN', '俄罗斯', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'RO', 'ROMANIAN', '罗马尼亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'RS', 'SERBIAN', '塞尔维亚', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'RW', 'RWANDAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SA', 'SAUDI ARABIAN', '沙特阿拉伯', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SB', 'SOLOMON ISLANDER', '所罗门群岛', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SC', 'SEYCHELLOIS', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SD', 'SUDANESE', '苏丹', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SE', 'SWEDISH', '瑞典', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SG', 'SINGAPORE', '新加坡', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SI', 'SLOVENIAN', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SK', 'SLOVAK', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SL', 'SIERRA LEONE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SM', 'SAMMARINESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SN', 'SENEGALESE', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SO', 'SOMALI', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SR', 'SURINAMER', NULL, 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO CM_MASTERCODE (CODE_ID, CODE_TYPE, CODE_VALUE, PROFILE, DESCRIPTION, IS_CACHED, IS_SYSTEM, DISPLAY_ORDER,
                           IS_ADMINABLE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cr.nationality', 'SS', 'STATELESS', '无国籍者', 'Y', 'Y', 0, 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

