INSERT INTO STA_STAFF (GENDER,
                       RESIGN_DATE, DEPARTMENT_ID, PHONE_NO, JOINED_DATE, CREATED_AT, EMAIL_ADDRESS, NICKNAME,
                       UPDATED_AT, QQ, POSITION_LEVEL, UPDATED_BY, STAFF_NO, PROFILE, WECHAT, PORTRAIT, ENTRY_NO,
                       POSITION_ID, CREATED_BY, DOB, PORTRAIT_EXT, NAME, PROJECT_ID, ID, AGE, STATUS)
VALUES ('M', NULL, 5, '13218149131', NOW(), NOW(), '351975711@qq.com', 'Minions', NOW(), NULL, 'H', 'SYSTEM', '205001',
        NULL, NULL, NULL, 1, 10, 'SYSTEM', NOW(), NULL, 'DAFU', 1, NULL, 25, 'A')
