CREATE TABLE AC_ROLE
(
    ROLE_ID      VARCHAR(8) PRIMARY KEY,
    ROLE_NAME    VARCHAR(32)  NOT NULL,
    TYPE         CHAR(3)      NOT NULL,
    PROFILE      VARCHAR(64),
    DESCRIPTION  VARCHAR(100),
    IS_SYSTEM    CHAR(1),
    LANDING_PAGE VARCHAR(512) NOT NULL,
    CREATED_AT   DATETIME     NOT NULL,
    CREATED_BY   VARCHAR(32)  NOT NULL,
    UPDATED_AT   DATETIME     NOT NULL,
    UPDATED_BY   VARCHAR(32)  NOT NULL
);