CREATE TABLE AC_ROLE
(
    ROLE_ID      VARCHAR(8) PRIMARY KEY,
    ROLE_NAME    VARCHAR(32)  NOT NULL,
    TYPE         CHAR(3)      NOT NULL,
    PROFILE      VARCHAR(64),
    DESCRIPTION  VARCHAR(100),
    IS_SYSTEM    CHAR(1),
    LANDING_PAGE VARCHAR(512) NOT NULL,
    CREATED_AT   DATETIME     NOT NULL,
    CREATED_BY   VARCHAR(32)  NOT NULL,
    UPDATED_AT   DATETIME     NOT NULL,
    UPDATED_BY   VARCHAR(32)  NOT NULL
);

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILE, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('STAFF', 'STAFF', 'IRS', '普通员工', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILE, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('PL', 'PROJECT LEADER', 'IRS', '项目主管', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILE, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('PM', 'PROJECT MANAGER', 'IRS', '项目经理', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILE, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('DEPTMGR', 'DEPARTMENT MANAGER', 'IRS', '部门经理', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILE, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('HR', 'HUMAN RESOURCE', 'IRS', '人事', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILE, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('HRMGR', 'HR MANAGER', 'IRS', '人事经理', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ROLE_ID, ROLE_NAME, TYPE, PROFILE, DESCRIPTION, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('OUTSTAFF', 'Outsourcing Satff', 'OSS', '外包员工', 'N', '/web/home', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
