CREATE TABLE AC_STUDENT_PROFILE
(
    USER_ID                 BIGINT      NOT NULL,
    ID_NO                   VARCHAR(16) NOT NULL,
    NAME                    VARCHAR(24) NOT NULL,
    DOB                     DATE,
    AGE                     INT,
    GENDER                  CHAR(1),
    ID_CARD_NO              VARCHAR(18) NOT NULL,
    HOME_ADDRESS            VARCHAR(100),
    DOMICILE                VARCHAR(16),
    NATIVE_PLACE            VARCHAR(16),
    NATION                  VARCHAR(6),
    COLLEGE                 VARCHAR(6)  NOT NULL,
    MAJOR                   VARCHAR(6)  NOT NULL,
    GRADE                   INT         NOT NULL,
    DEGREE_IN_STUDY         CHAR(3)     NOT NULL,
    IS_STUDYING             CHAR(1),
    IS_GRADUATED            CHAR(1),
    IS_GRADUATION_POSTPONED CHAR(1),
    EXPECTED_GRADUATE_YEAR  VARCHAR(4)  NOT NULL,
    ACTUAL_GRADUATE_YEAR    VARCHAR(4),
    ENTRANCE_YEAR           VARCHAR(4),
    DORMITORY               VARCHAR(16) NOT NULL,
    PROFILE                 VARCHAR(500),
    CREATED_AT              DATETIME    NOT NULL,
    CREATED_BY              VARCHAR(24) NOT NULL,
    UPDATED_AT              DATETIME    NOT NULL,
    UPDATED_BY              VARCHAR(24) NOT NULL
);

ALTER TABLE AC_STUDENT_PROFILE
    ADD CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES AC_USER_ACCT (USER_ID);

CREATE TABLE AC_STUDENT_PROFILE_H
(
    AUDIT_ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUDIT_TYPE              CHAR(2),
    AUDIT_TIME              DATETIME,
    USER_ID                 BIGINT,
    ID_NO                   VARCHAR(16),
    NAME                    VARCHAR(24),
    DOB                     DATE,
    AGE                     INT,
    GENDER                  CHAR(1),
    ID_CARD_NO              VARCHAR(18),
    HOME_ADDRESS            VARCHAR(100),
    DOMICILE                VARCHAR(16),
    NATIVE_PLACE            VARCHAR(16),
    NATION                  VARCHAR(6),
    COLLEGE                 VARCHAR(6),
    MAJOR                   VARCHAR(6),
    GRADE                   INT,
    DEGREE_IN_STUDY         CHAR(3),
    IS_STUDYING             CHAR(1),
    IS_GRADUATED            CHAR(1),
    IS_GRADUATION_POSTPONED CHAR(1),
    EXPECTED_GRADUATE_YEAR  VARCHAR(4),
    ACTUAL_GRADUATE_YEAR    VARCHAR(4),
    ENTRANCE_YEAR           VARCHAR(4),
    DORMITORY               VARCHAR(16),
    PROFILE                 VARCHAR(500),
    CREATED_AT              DATETIME,
    CREATED_BY              VARCHAR(24),
    UPDATED_AT              DATETIME,
    UPDATED_BY              VARCHAR(24)
);


DELIMITER ##
CREATE TRIGGER AC_STUDENT_PROFILE_TRG_AI
    AFTER INSERT
    ON AC_STUDENT_PROFILE
    FOR EACH ROW
BEGIN
    INSERT INTO AC_STUDENT_PROFILE_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                     USER_ID, ID_NO, NAME, DOB, AGE, GENDER,
                                     ID_CARD_NO, HOME_ADDRESS, DOMICILE, NATIVE_PLACE, NATION,
                                     COLLEGE, MAJOR, GRADE, DEGREE_IN_STUDY, IS_STUDYING,
                                     IS_GRADUATED, IS_GRADUATION_POSTPONED, EXPECTED_GRADUATE_YEAR,
                                     ACTUAL_GRADUATE_YEAR, ENTRANCE_YEAR,
                                     DORMITORY, PROFILE, CREATED_AT, CREATED_BY, UPDATED_AT,
                                     UPDATED_BY)
    VALUES (NULL, 'AI', NOW(),
            NEW.USER_ID, NEW.ID_NO, NEW.NAME, NEW.DOB, NEW.AGE, NEW.GENDER,
            NEW.ID_CARD_NO, NEW.HOME_ADDRESS, NEW.DOMICILE, NEW.NATIVE_PLACE, NEW.NATION,
            NEW.COLLEGE, NEW.MAJOR, NEW.GRADE, NEW.DEGREE_IN_STUDY, NEW.IS_STUDYING,
            NEW.IS_GRADUATED, NEW.IS_GRADUATION_POSTPONED, NEW.EXPECTED_GRADUATE_YEAR, NEW.ACTUAL_GRADUATE_YEAR,
            NEW.ENTRANCE_YEAR,
            NEW.DORMITORY, NEW.PROFILE, NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT,
            NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER AC_STUDENT_PROFILE_TRG_BU
    BEFORE UPDATE
    ON AC_STUDENT_PROFILE
    FOR EACH ROW
BEGIN
    INSERT INTO AC_STUDENT_PROFILE_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                     USER_ID, ID_NO, NAME, DOB, AGE, GENDER,
                                     ID_CARD_NO, HOME_ADDRESS, DOMICILE, NATIVE_PLACE, NATION,
                                     COLLEGE, MAJOR, GRADE, DEGREE_IN_STUDY, IS_STUDYING,
                                     IS_GRADUATED, IS_GRADUATION_POSTPONED, EXPECTED_GRADUATE_YEAR,
                                     ACTUAL_GRADUATE_YEAR, ENTRANCE_YEAR,
                                     DORMITORY, PROFILE, CREATED_AT, CREATED_BY, UPDATED_AT,
                                     UPDATED_BY)
    VALUES (NULL, 'BU', NOW(),
            OLD.USER_ID, OLD.ID_NO, OLD.NAME, OLD.DOB, OLD.AGE, OLD.GENDER,
            OLD.ID_CARD_NO, OLD.HOME_ADDRESS, OLD.DOMICILE, OLD.NATIVE_PLACE, OLD.NATION,
            OLD.COLLEGE, OLD.MAJOR, OLD.GRADE, OLD.DEGREE_IN_STUDY, OLD.IS_STUDYING,
            OLD.IS_GRADUATED, OLD.IS_GRADUATION_POSTPONED, OLD.EXPECTED_GRADUATE_YEAR, OLD.ACTUAL_GRADUATE_YEAR,
            OLD.ENTRANCE_YEAR,
            OLD.DORMITORY, OLD.PROFILE, OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT,
            OLD.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER AC_STUDENT_PROFILE_TRG_AU
    AFTER UPDATE
    ON AC_STUDENT_PROFILE
    FOR EACH ROW
BEGIN
    INSERT INTO AC_STUDENT_PROFILE_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                     USER_ID, ID_NO, NAME, DOB, AGE, GENDER,
                                     ID_CARD_NO, HOME_ADDRESS, DOMICILE, NATIVE_PLACE, NATION,
                                     COLLEGE, MAJOR, GRADE, DEGREE_IN_STUDY, IS_STUDYING,
                                     IS_GRADUATED, IS_GRADUATION_POSTPONED, EXPECTED_GRADUATE_YEAR,
                                     ACTUAL_GRADUATE_YEAR, ENTRANCE_YEAR,
                                     DORMITORY, PROFILE, CREATED_AT, CREATED_BY, UPDATED_AT,
                                     UPDATED_BY)
    VALUES (NULL, 'AU', NOW(),
            NEW.USER_ID, NEW.ID_NO, NEW.NAME, NEW.DOB, NEW.AGE, NEW.GENDER,
            NEW.ID_CARD_NO, NEW.HOME_ADDRESS, NEW.DOMICILE, NEW.NATIVE_PLACE, NEW.NATION,
            NEW.COLLEGE, NEW.MAJOR, NEW.GRADE, NEW.DEGREE_IN_STUDY, NEW.IS_STUDYING,
            NEW.IS_GRADUATED, NEW.IS_GRADUATION_POSTPONED, NEW.EXPECTED_GRADUATE_YEAR, NEW.ACTUAL_GRADUATE_YEAR,
            NEW.ENTRANCE_YEAR,
            NEW.DORMITORY, NEW.PROFILE, NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT,
            NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER AC_STUDENT_PROFILE_TRG_BD
    BEFORE DELETE
    ON AC_STUDENT_PROFILE
    FOR EACH ROW
BEGIN
    INSERT INTO AC_STUDENT_PROFILE_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                     USER_ID, ID_NO, NAME, DOB, AGE, GENDER,
                                     ID_CARD_NO, HOME_ADDRESS, DOMICILE, NATIVE_PLACE, NATION,
                                     COLLEGE, MAJOR, GRADE, DEGREE_IN_STUDY, IS_STUDYING,
                                     IS_GRADUATED, IS_GRADUATION_POSTPONED, EXPECTED_GRADUATE_YEAR,
                                     ACTUAL_GRADUATE_YEAR, ENTRANCE_YEAR,
                                     DORMITORY, PROFILE, CREATED_AT, CREATED_BY, UPDATED_AT,
                                     UPDATED_BY)
    VALUES (NULL, 'BD', NOW(),
            OLD.USER_ID, OLD.ID_NO, OLD.NAME, OLD.DOB, OLD.AGE, OLD.GENDER,
            OLD.ID_CARD_NO, OLD.HOME_ADDRESS, OLD.DOMICILE, OLD.NATIVE_PLACE, OLD.NATION,
            OLD.COLLEGE, OLD.MAJOR, OLD.GRADE, OLD.DEGREE_IN_STUDY, OLD.IS_STUDYING,
            OLD.IS_GRADUATED, OLD.IS_GRADUATION_POSTPONED, OLD.EXPECTED_GRADUATE_YEAR, OLD.ACTUAL_GRADUATE_YEAR,
            OLD.ENTRANCE_YEAR,
            OLD.DORMITORY, OLD.PROFILE, OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT,
            OLD.UPDATED_BY);
END ##
DELIMITER ;