CREATE TABLE AC_USER_LOGIN_HIS
(
    USER_ID      BIGINT      NOT NULL,
    ACCT_STATUS  CHAR(1)     NOT NULL,
    LOGIN_AT     DATETIME    NOT NULL,
    LOGIN_STATUS CHAR(1)     NOT NULL,
    IP_ADDRESS   VARCHAR(32),
    IP_BELONG_TO VARCHAR(16),
    BROWSER      VARCHAR(128),
    CREATED_AT   DATETIME    NOT NULL,
    CREATED_BY   VARCHAR(24) NOT NULL,
    UPDATED_AT   DATETIME    NOT NULL,
    UPDATED_BY   VARCHAR(24) NOT NULL,
    INDEX LOGIN_HIS_IDX (USER_ID)
);