CREATE TABLE CL_TC_CS_ARRANGEMENT
(
    TC_CS_ID     BIGINT PRIMARY KEY AUTO_INCREMENT,
    COURSE_CODE  VARCHAR(16) NOT NULL,
    FROM_COLLEGE VARCHAR(6)  NOT NULL,
    FOR_COLLEGE  VARCHAR(6)  NOT NULL,
    TEACHER      VARCHAR(16) NOT NULL,
    SCHEDULE     VARCHAR(32) NOT NULL,
    ARRANGED_BY  VARCHAR(16),
    STATUS       VARCHAR(16) NOT NULL,
    REMARKS      VARCHAR(100),
    CREATED_AT   DATETIME    NOT NULL,
    CREATED_BY   VARCHAR(32) NOT NULL,
    UPDATED_AT   DATETIME    NOT NULL,
    UPDATED_BY   VARCHAR(32) NOT NULL
);