CREATE TABLE CM_COLLEGE
(
    COLLEGE_ID         INT PRIMARY KEY AUTO_INCREMENT,
    COLLEGE_CODE       VARCHAR(6)  NOT NULL UNIQUE,
    NAME               VARCHAR(16) NOT NULL,
    SUBJECT_TYPE       CHAR(1),
    DEAN               VARCHAR(16),
    DEAN_ID            VARCHAR(16),
    CONTACT_NO         VARCHAR(16),
    ESTABLISH_TIME     DATE,
    IS_RECRUITING      CHAR(1),
    IS_KEY             CHAR(1),
    NUMBER_OF_STUDENTS INT,
    NUMBER_OF_STAFFS   INT,
    CREATED_AT         DATETIME    NOT NULL,
    CREATED_BY         VARCHAR(24) NOT NULL,
    UPDATED_AT         DATETIME    NOT NULL,
    UPDATED_BY         VARCHAR(24) NOT NULL
);