CREATE TABLE CM_MASTERCODE
(
    CODE_ID       INT PRIMARY KEY AUTO_INCREMENT,
    CODE_TYPE     VARCHAR(64) NOT NULL,
    CODE_VALUE    VARCHAR(64) NOT NULL,
    PROFILE       VARCHAR(100),
    DESCRIPTION   VARCHAR(500),
    IS_CACHED     CHAR(1)     NOT NULL,
    IS_SYSTEM     CHAR(1),
    DISPLAY_ORDER INT,
    IS_ADMINABLE  CHAR(1)     NOT NULL,
    CREATED_AT    DATETIME    NOT NULL,
    CREATED_BY    VARCHAR(32) NOT NULL,
    UPDATED_AT    DATETIME    NOT NULL,
    UPDATED_BY    VARCHAR(32) NOT NULL
);