CREATE TABLE CM_MASTERCODE
(
    MASTERCODE_ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE          VARCHAR(64) NOT NULL,
    CODE          VARCHAR(16) NOT NULL,
    VALUE         VARCHAR(64) NOT NULL,
    DESCRIPTION   VARCHAR(500),
    IS_CACHED     CHAR(1)     NOT NULL,
    IS_SYSTEM     CHAR(1),
    DISPLAY_ORDER INT,
    IS_ADMINABLE  CHAR(1)     NOT NULL,
    CREATED_AT    DATETIME    NOT NULL,
    CREATED_BY    VARCHAR(32) NOT NULL,
    UPDATED_AT    DATETIME    NOT NULL,
    UPDATED_BY    VARCHAR(32) NOT NULL,
    UNIQUE TYPE_VALUE_UK (TYPE, CODE)
);

INSERT INTO CM_MASTERCODE (MASTERCODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, IS_ADMINABLE,
                           DISPLAY_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.recruitment.type', 'SCH', '校园招聘', NULL, 'Y', 'N', 'Y', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (MASTERCODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, IS_ADMINABLE,
                           DISPLAY_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.recruitment.type', 'SOC', '社会招聘', NULL, 'Y', 'N', 'Y', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (MASTERCODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, IS_ADMINABLE,
                           DISPLAY_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.recruitment.type', 'HUN', '猎头招聘', NULL, 'Y', 'N', 'Y', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (MASTERCODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, IS_ADMINABLE,
                           DISPLAY_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.recruitment.type', 'INT', '内部招聘', NULL, 'Y', 'N', 'Y', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (MASTERCODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, IS_ADMINABLE,
                           DISPLAY_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.recruitment.type', 'REC', '机构推荐', NULL, 'Y', 'N', 'Y', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');



INSERT INTO CM_MASTERCODE (MASTERCODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, IS_ADMINABLE,
                           DISPLAY_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.political.status', '00', '无', NULL, 'Y', 'N', 'Y', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (MASTERCODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, IS_ADMINABLE,
                           DISPLAY_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.political.status', 'CYL', '共青团员', NULL, 'Y', 'N', 'Y', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_MASTERCODE (MASTERCODE_ID, TYPE, CODE, VALUE, DESCRIPTION, IS_CACHED, IS_SYSTEM, IS_ADMINABLE,
                           DISPLAY_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (NULL, 'cm.political.status', 'CCP', '共产党员', NULL, 'Y', 'N', 'Y', 0, NOW(), 'SYSTEM', NOW(), 'SYSTEM');