CREATE TABLE CM_PUBLIC_HOLIDAY
(
    NAME       VARCHAR(64) NOT NULL,
    YEAR       INT         NOT NULL,
    MONTH      INT         NOT NULL,
    START      DATE        NOT NULL,
    END        DATE        NOT NULL,
    CREATED_AT DATETIME    NOT NULL,
    CREATED_BY VARCHAR(32) NOT NULL,
    UPDATED_AT DATETIME    NOT NULL,
    UPDATED_BY VARCHAR(32) NOT NULL
);