CREATE TABLE CM_SEQUENCE
(
    NAME        VARCHAR(6) PRIMARY KEY,
    VALUE       BIGINT NOT NULL DEFAULT 0,
    MIN_VALUE   BIGINT NOT NULL DEFAULT 0,
    MAX_VALUE   BIGINT,
    STEP        INT    NOT NULL DEFAULT 1,
    DESCRIPTION VARCHAR(100)
);

INSERT INTO CM_SEQUENCE(NAME, VALUE, MIN_VALUE, MAX_VALUE, DESCRIPTION)
VALUES ('STAFF_ID', 1, 0, NULL, NULL);

INSERT INTO CM_SEQUENCE(NAME, VALUE, MIN_VALUE, MAX_VALUE, DESCRIPTION)
VALUES ('ENTRY_NO', 1, 0, NULL, NULL);