CREATE TABLE MC_DEPARTMENT
(
    DEPARTMENT_ID      VARCHAR(6) PRIMARY KEY,
    DEPARTMENT_NAME    VARCHAR(64) NOT NULL,
    DESCRIPTION        VARCHAR(100),
    APPRAISE_PREFIX    CHAR(1)     NOT NULL,
    APPRAISE_LEVEL     INT         NOT NULL,
    NUMBER_OF_STAFF    INT,
    CREATED_AT         DATETIME    NOT NULL,
    CREATED_BY         VARCHAR(32) NOT NULL,
    UPDATED_AT         DATETIME    NOT NULL,
    UPDATED_BY         VARCHAR(32) NOT NULL
);