CREATE TABLE MC_DEPARTMENT
(
    DEPARTMENT_ID   VARCHAR(6) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(64) NOT NULL,
    DESCRIPTION     VARCHAR(100),
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_BY      VARCHAR(32) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_BY      VARCHAR(32) NOT NULL
);

INSERT INTO MC_DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('10001', '软件与应用开发部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('10002', '软件产品研发部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('20001', '产品部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('30001', '市场营销部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('40001', '人力资源部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('50001', '财政部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');