CREATE TABLE MC_DISTRICT
(
    ID         INT(11) PRIMARY KEY,
    PARENT_ID  INT(11)     NOT NULL,
    NAME       VARCHAR(50) NOT NULL,
    SHORT_NAME VARCHAR(50) NOT NULL,
    LONGITUDE  FLOAT       NOT NULL,
    LATITUDE   FLOAT       NOT NULL,
    LEVEL      INT(1)      NOT NULL,
    SORT       INT(3)      NOT NULL,
    STATUS     INT(1)      NOT NULL
);