CREATE TABLE MC_DEPARTMENT
(
    ID   INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(64) NOT NULL,
    DESCRIPTION     VARCHAR(100),
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_BY      VARCHAR(32) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_BY      VARCHAR(32) NOT NULL
);

INSERT INTO MC_DEPARTMENT (ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (1, '软件与应用开发部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (2, '软件产品研发部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (3, '产品部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (4, '市场营销部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (5, '人力资源部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_DEPARTMENT (ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (6, '财政部', NULL, NOW(), 'SYSTEM', NOW(), 'SYSTEM');