CREATE TABLE MC_POSITION
(
    ID              INT PRIMARY KEY AUTO_INCREMENT,
    DEPARTMENT_ID   INT         NOT NULL,
    ROLE_ID         VARCHAR(8)  NOT NULL,
    POSITION_NAME   VARCHAR(64) NOT NULL,
    DESCRIPTION     VARCHAR(100),
    APPRAISE_PREFIX CHAR(1)     NOT NULL,
    APPRAISE_LEVEL  INT         NOT NULL,
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_BY      VARCHAR(32) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_BY      VARCHAR(32) NOT NULL
);

ALTER TABLE MC_POSITION
    ADD CONSTRAINT POSITION_DEPARTMENT_ID_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES MC_DEPARTMENT (ID);

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '软件开发工程师', NULL, 1, 'D', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'SFTENG');

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '项目主管', NULL, 1, 'P', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'PL');

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '项目经理', NULL, 1, 'P', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'PM');

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '产品研发工程师', NULL, 2, 'R', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'SFTENG');

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '项目主管', NULL, 2, 'P', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'PL');

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '项目经理', NULL, 2, 'P', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'PM');

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '软件测试工程师', NULL, 1, 'Q', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'QA');

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '软件测试工程师', NULL, 2, 'Q', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'QA');

INSERT INTO MC_POSITION (ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, ROLE_ID)
VALUES (NULL, '人力资源', NULL, 5, 'H', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'HR');
