CREATE TABLE MC_PROJECT
(
    ID             INT PRIMARY KEY AUTO_INCREMENT,
    NAME           VARCHAR(64) NOT NULL,
    TYPE           CHAR(3)     NOT NULL,
    NATURE         CHAR(3)     NOT NULL,
    PL             VARCHAR(16),
    PM             VARCHAR(16),
    REQ_START_DATE DATE,
    REQ_END_DATE   DATE,
    DEV_START_DATE DATE,
    DEV_END_DATE   DATE,
    SIT_START_DATE DATE,
    SIT_END_DATE   DATE,
    UAT_START_DATE DATE,
    UAT_END_DATE   DATE,
    DESCRIPTION    VARCHAR(4000),
    CREATED_AT     DATETIME    NOT NULL,
    CREATED_BY     VARCHAR(32) NOT NULL,
    UPDATED_AT     DATETIME    NOT NULL,
    UPDATED_BY     VARCHAR(32) NOT NULL

);

INSERT INTO MC_PROJECT (NAME, TYPE, NATURE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('TEST', 'DEV', 'INTERNAL', NOW(), 'SYSTEM', NOW(), 'SYSTEM');