CREATE TABLE MC_POSITION
(
    POSITION_ID     VARCHAR(6) PRIMARY KEY,
    DEPARTMENT_ID   VARCHAR(6)  NOT NULL,
    POSITION_NAME   VARCHAR(64) NOT NULL,
    DESCRIPTION     VARCHAR(100),
    APPRAISE_PREFIX CHAR(1)     NOT NULL,
    APPRAISE_LEVEL  INT         NOT NULL,
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_BY      VARCHAR(32) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_BY      VARCHAR(32) NOT NULL
);

ALTER TABLE MC_POSITION ADD CONSTRAINT POSITION_DEPARTMENT_ID_FK  FOREIGN KEY (DEPARTMENT_ID) REFERENCES MC_DEPARTMENT (DEPARTMENT_ID);

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1001', '软件开发工程师', NULL, '10001', 'D', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1005', '项目主管', NULL, '10001', 'D', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1006', '项目经理', NULL, '10001', 'D', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1002', '软件研发工程师', NULL, '10002', 'R', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1007', '项目主管', NULL, '10002', 'D', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1008', '项目经理', NULL, '10002', 'D', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1003', '软件测试工程师', NULL, '10001', 'Q', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1004', '软件测试工程师', NULL, '10002', 'Q', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO MC_POSITION (POSITION_ID, POSITION_NAME, DESCRIPTION, DEPARTMENT_ID, APPRAISE_PREFIX, APPRAISE_LEVEL,
                         CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('1009', '人力资源', NULL, '40001', 'Q', 10, NOW(), 'SYSTEM', NOW(), 'SYSTEM');
