CREATE TABLE MC_SUBJECT
(
    SUBJECT_ID  VARCHAR(6) PRIMARY KEY,
    LEVEL1_ID   VARCHAR(6)   NOT NULL,
    LEVEL2_ID   VARCHAR(6)   NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    CREATED_AT  DATETIME     NOT NULL,
    CREATED_BY  VARCHAR(32)  NOT NULL,
    UPDATED_AT  DATETIME     NOT NULL,
    UPDATED_BY  VARCHAR(32)  NOT NULL
);