CREATE TABLE MJO_CURRICULUM_PLAN
(

    MAJOR_CODE       VARCHAR(6)  NOT NULL,
    COURSE_CODE      VARCHAR(16) NOT NULL,
    SCHEDULE_GRADE   INT         NOT NULL,
    IS_CORE          CHAR(1) DEFAULT 'N',
    IS_COMPULSORY    CHAR(1) DEFAULT 'N',
    IS_OPTIONAL      CHAR(1) DEFAULT 'N',
    IS_GENERAL       CHAR(1) DEFAULT 'N',
    IS_PROFESSIONAL  CHAR(1) DEFAULT 'N',
    START_WEEK       INT         NOT NULL,
    LESSONS          INT         NOT NULL,
    LESSONS_PER_WEEK INT         NOT NULL,
    CREDIT           DOUBLE      NOT NULL,
    APPRAISE_TYPE    CHAR(1)     NOT NULL,
    WEIGHT           DOUBLE,
    CREATED_AT       DATETIME    NOT NULL,
    CREATED_BY       VARCHAR(32) NOT NULL,
    UPDATED_AT       DATETIME    NOT NULL,
    UPDATED_BY       VARCHAR(32) NOT NULL,
    PRIMARY KEY MJO_CURRICULUM_PLAN_PK (MAJOR_CODE, COURSE_CODE)
);