CREATE TABLE SA_ANNOUNCEMENT
(
    ANNOUNCEMENT_NO VARCHAR(16) UNIQUE NOT NULL,
    TYPE            VARCHAR(16)        NOT NULL,
    TITLE           VARCHAR(50)        NOT NULL,
    CONTENT         MEDIUMBLOB         NOT NULL,
    TARGET_COLLEGE  VARCHAR(6)         NOT NULL,
    TARGET_MAJOR    VARCHAR(6)         NOT NULL,
    TARGET_CLASS    VARCHAR(6)         NOT NULL,
    TARGET_ROLE     VARCHAR(6)         NOT NULL,
    FROM_DATE       DATETIME           NOT NULL,
    TO_DATE         DATETIME           NOT NULL,
    CREATED_AT      DATETIME           NOT NULL,
    CREATED_BY      VARCHAR(32)        NOT NULL,
    UPDATED_AT      DATETIME           NOT NULL,
    UPDATED_BY      VARCHAR(32)        NOT NULL
);