CREATE TABLE SA_BATCH_JOB_STATUS
(
    BATCH_JOB_STATUS_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BATCH_JOB_ID        VARCHAR(32) NOT NULL,
    START_AT            DATETIME,
    END_AT              DATETIME,
    STATUS              VARCHAR(32) NOT NULL,
    TRIGGERED_BY        VARCHAR(32) NOT NULL,
    CREATED_AT          DATETIME    NOT NULL,
    CREATED_BY          VARCHAR(32) NOT NULL,
    UPDATED_AT          DATETIME    NOT NULL,
    UPDATED_BY          VARCHAR(32) NOT NULL

);