CREATE TABLE SA_FAILED_BATCH_JOB
(
    FAILED_BATCH_JOB_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BATCH_JOB_ID        VARCHAR(32) NOT NULL,
    START_AT            DATETIME    NOT NULL,
    END_AT              DATETIME    NOT NULL,
    EXCEPTION           MEDIUMBLOB,
    IS_IGNORED          CHAR(1),
    CREATED_AT          DATETIME    NOT NULL,
    CREATED_BY          VARCHAR(32) NOT NULL,
    UPDATED_AT          DATETIME    NOT NULL,
    UPDATED_BY          VARCHAR(32) NOT NULL
);