CREATE TABLE SA_FAILED_EMAIL
(
    FAILED_EMAIL_ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    SENT_FROM         VARCHAR(64)   NOT NULL,
    SENT_TO           VARCHAR(1024) NOT NULL,
    CC                VARCHAR(1024),
    SUBJECT           VARCHAR(500)  NOT NULL,
    CONTENT           MEDIUMBLOB,
    IS_HAS_ATTACHMENT CHAR(1),
    FAILED_TIMES      INT           NOT NULL,
    LAST_FAILED_TIME  DATETIME      NOT NULL,
    FAILED_REASON     VARCHAR(1000),
    STATUS            VARCHAR(16),
    CREATED_AT        DATETIME      NOT NULL,
    CREATED_BY        VARCHAR(32)   NOT NULL,
    UPDATED_AT        DATETIME      NOT NULL,
    UPDATED_BY        VARCHAR(32)   NOT NULL
);