CREATE TABLE SA_FAILED_EMAIL
(
    ID_NO              VARCHAR(16)  NOT NULL,
    SENT_FROM          VARCHAR(64)  NOT NULL,
    SENT_TO            VARCHAR(64)  NOT NULL,
    SUBJECT            VARCHAR(500) NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(128),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    FAILED_TIMES       INT          NOT NULL,
    LAST_FAILED_TIME   DATETIME     NOT NULL,
    FAILED_REASON      VARCHAR(1000),
    CREATED_AT         DATETIME     NOT NULL,
    CREATED_BY         VARCHAR(32)  NOT NULL,
    UPDATED_AT         DATETIME     NOT NULL,
    UPDATED_BY         VARCHAR(32)  NOT NULL
);