CREATE TABLE SA_STU_INTERNAL_EMAIL_INBOX
(
    STU_NO             VARCHAR(16)  NOT NULL,
    SENT_FROM          VARCHAR(64)  NOT NULL,
    SENT_TO            VARCHAR(64)  NOT NULL,
    TITLE              VARCHAR(500) NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(128),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    CREATED_AT         DATETIME     NOT NULL,
    CREATED_BY         VARCHAR(32)  NOT NULL,
    UPDATED_AT         DATETIME     NOT NULL,
    UPDATED_BY         VARCHAR(32)  NOT NULL
);

CREATE TABLE SA_STU_INTERNAL_EMAIL_SENT
(
    STU_NO             VARCHAR(16)  NOT NULL,
    SENT_FROM          VARCHAR(64)  NOT NULL,
    SENT_TO            VARCHAR(64)  NOT NULL,
    TITLE              VARCHAR(500) NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(128),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    CREATED_AT         DATETIME     NOT NULL,
    CREATED_BY         VARCHAR(32)  NOT NULL,
    UPDATED_AT         DATETIME     NOT NULL,
    UPDATED_BY         VARCHAR(32)  NOT NULL
);

CREATE TABLE SA_STU_INTERNAL_EMAIL_READ
(
    STU_NO             VARCHAR(16)  NOT NULL,
    SENT_FROM          VARCHAR(64)  NOT NULL,
    SENT_TO            VARCHAR(64)  NOT NULL,
    TITLE              VARCHAR(500) NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(128),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    CREATED_AT         DATETIME     NOT NULL,
    CREATED_BY         VARCHAR(32)  NOT NULL,
    UPDATED_AT         DATETIME     NOT NULL,
    UPDATED_BY         VARCHAR(32)  NOT NULL
);

CREATE TABLE SA_STU_INTERNAL_EMAIL_RECYCLED
(
    STU_NO             VARCHAR(16)  NOT NULL,
    SENT_FROM          VARCHAR(64)  NOT NULL,
    SENT_TO            VARCHAR(64)  NOT NULL,
    TITLE              VARCHAR(500) NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(128),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    CREATED_AT         DATETIME     NOT NULL,
    CREATED_BY         VARCHAR(32)  NOT NULL,
    UPDATED_AT         DATETIME     NOT NULL,
    UPDATED_BY         VARCHAR(32)  NOT NULL
);