CREATE TABLE SA_STU_INTERNAL_EMAIL_INBOX
(
    EMAIL_ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    SENT_FROM          VARCHAR(64)   NOT NULL,
    SENT_TO            VARCHAR(1024) NOT NULL,
    CC                 VARCHAR(1024),
    SUBJECT            VARCHAR(500)  NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(512),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    STATUS             VARCHAR(32),
    CREATED_AT         DATETIME      NOT NULL,
    CREATED_BY         VARCHAR(32)   NOT NULL,
    UPDATED_AT         DATETIME      NOT NULL,
    UPDATED_BY         VARCHAR(32)   NOT NULL
);

CREATE TABLE SA_STU_INTERNAL_EMAIL_SENT
(
    EMAIL_ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    SENT_FROM          VARCHAR(64)   NOT NULL,
    SENT_TO            VARCHAR(1024) NOT NULL,
    CC                 VARCHAR(1024),
    SUBJECT            VARCHAR(500)  NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(512),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    CREATED_AT         DATETIME      NOT NULL,
    CREATED_BY         VARCHAR(32)   NOT NULL,
    UPDATED_AT         DATETIME      NOT NULL,
    UPDATED_BY         VARCHAR(32)   NOT NULL
);

CREATE TABLE SA_STU_INTERNAL_EMAIL_READ
(
    EMAIL_ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    SENT_FROM          VARCHAR(64)   NOT NULL,
    SENT_TO            VARCHAR(1024) NOT NULL,
    CC                 VARCHAR(1024),
    SUBJECT            VARCHAR(500)  NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(512),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    STATUS             VARCHAR(32),
    CREATED_AT         DATETIME      NOT NULL,
    CREATED_BY         VARCHAR(32)   NOT NULL,
    UPDATED_AT         DATETIME      NOT NULL,
    UPDATED_BY         VARCHAR(32)   NOT NULL
);

CREATE TABLE SA_STU_INTERNAL_EMAIL_DRAFT
(
    EMAIL_ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    SENT_FROM          VARCHAR(64)   NOT NULL,
    SENT_TO            VARCHAR(1024) NOT NULL,
    CC                 VARCHAR(1024),
    SUBJECT            VARCHAR(500)  NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(512),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    STATUS             VARCHAR(32),
    CREATED_AT         DATETIME      NOT NULL,
    CREATED_BY         VARCHAR(32)   NOT NULL,
    UPDATED_AT         DATETIME      NOT NULL,
    UPDATED_BY         VARCHAR(32)   NOT NULL
);

CREATE TABLE SA_STU_INTERNAL_EMAIL_RECYCLED
(
    EMAIL_ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    SENT_FROM          VARCHAR(64)   NOT NULL,
    SENT_TO            VARCHAR(1024) NOT NULL,
    CC                 VARCHAR(1024),
    SUBJECT            VARCHAR(500)  NOT NULL,
    CONTENT            MEDIUMBLOB,
    ATTACHED_FILE_NAME VARCHAR(512),
    ATTACHED_FILE_ID   VARCHAR(512),
    ATTACHED_FILE_PATH VARCHAR(1024),
    STATUS             VARCHAR(32),
    CREATED_AT         DATETIME      NOT NULL,
    CREATED_BY         VARCHAR(32)   NOT NULL,
    UPDATED_AT         DATETIME      NOT NULL,
    UPDATED_BY         VARCHAR(32)   NOT NULL
);