CREATE TABLE SKD_CALENDAR_EVENT
(
    USER_ID          VARCHAR(16) NOT NULL,
    GROUP_ID         INT,
    TITLE            VARCHAR(50) NOT NULL,
    CONTENT          VARCHAR(500),
    EVENT_TYPE       VARCHAR(6)  NOT NULL,
    START            DATETIME    NOT NULL,
    END              DATETIME,
    COLOR            CHAR(7),
    TEXT_COLOR       CHAR(7),
    BACKGROUND_COLOR CHAR(7),
    ALL_DAY          CHAR(1),
    EDITABLE         CHAR(1),
    CREATED_AT       DATETIME    NOT NULL,
    CREATED_BY       VARCHAR(32) NOT NULL,
    UPDATED_AT       DATETIME    NOT NULL,
    UPDATED_BY       VARCHAR(32) NOT NULL,
    INDEX START_IDX (START),
    INDEX EVENT_USER_ID_IDX (USER_ID)
);