CREATE TABLE STA_STAFF_BASIC_SALARY
(
    STAFF_ID                 VARCHAR(16) NOT NULL,
    BASIC_SALARY             FLOAT       NOT NULL,
    CATERING_SUBSIDIES       FLOAT       NOT NULL DEFAULT 0,
    TRANSPORTATION_SUBSIDIES FLOAT       NOT NULL DEFAULT 0,
    DEVICES_SUBSIDIES        FLOAT       NOT NULL DEFAULT 0,
    POSITION_SUBSIDIES       FLOAT       NOT NULL DEFAULT 0,
    OTHER_SUBSIDIES          FLOAT       NOT NULL DEFAULT 0,
    BONUS                    FLOAT       NOT NULL DEFAULT 0,
    CREATED_AT               DATETIME    NOT NULL,
    CREATED_BY               VARCHAR(32) NOT NULL,
    UPDATED_AT               DATETIME    NOT NULL,
    UPDATED_BY               VARCHAR(32) NOT NULL
);

CREATE TABLE STA_STAFF_BASIC_SALARY_H
(
    AUDIT_ID                 BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUDIT_TYPE               CHAR(2),
    AUDIT_TIME               DATETIME,
    STAFF_ID                 VARCHAR(16),
    BASIC_SALARY             FLOAT,
    CATERING_SUBSIDIES       FLOAT,
    TRANSPORTATION_SUBSIDIES FLOAT,
    DEVICES_SUBSIDIES        FLOAT,
    POSITION_SUBSIDIES       FLOAT,
    OTHER_SUBSIDIES          FLOAT,
    BONUS                    FLOAT,
    CREATED_AT               DATETIME,
    CREATED_BY               VARCHAR(32),
    UPDATED_AT               DATETIME,
    UPDATED_BY               VARCHAR(32)
);

DELIMITER ##
CREATE TRIGGER STA_STAFF_BASIC_SALARY_TRG_AI
    AFTER INSERT
    ON STA_STAFF_BASIC_SALARY
    FOR EACH ROW
BEGIN
    INSERT INTO STA_STAFF_BASIC_SALARY_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                         STAFF_ID, BASIC_SALARY, CATERING_SUBSIDIES, TRANSPORTATION_SUBSIDIES,
                                         DEVICES_SUBSIDIES, POSITION_SUBSIDIES,
                                         OTHER_SUBSIDIES, BONUS, CREATED_AT, CREATED_BY, UPDATED_AT,
                                         UPDATED_BY)
    VALUES (NULL, 'AI', NOW(),
            NEW.STAFF_ID, NEW.BASIC_SALARY, NEW.CATERING_SUBSIDIES, NEW.TRANSPORTATION_SUBSIDIES, NEW.DEVICES_SUBSIDIES,
            NEW.POSITION_SUBSIDIES,
            NEW.OTHER_SUBSIDIES, NEW.BONUS, NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT,
            NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STA_STAFF_BASIC_SALARY_TRG_BU
    BEFORE UPDATE
    ON STA_STAFF_BASIC_SALARY
    FOR EACH ROW
BEGIN
    INSERT INTO STA_STAFF_BASIC_SALARY_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                         STAFF_ID, BASIC_SALARY, CATERING_SUBSIDIES, TRANSPORTATION_SUBSIDIES,
                                         DEVICES_SUBSIDIES, POSITION_SUBSIDIES,
                                         OTHER_SUBSIDIES, BONUS, CREATED_AT, CREATED_BY, UPDATED_AT,
                                         UPDATED_BY)
    VALUES (NULL, 'BU', NOW(),
            OLD.STAFF_ID, OLD.BASIC_SALARY, OLD.CATERING_SUBSIDIES, OLD.TRANSPORTATION_SUBSIDIES, OLD.DEVICES_SUBSIDIES,
            OLD.POSITION_SUBSIDIES,
            OLD.OTHER_SUBSIDIES, OLD.BONUS, OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT,
            OLD.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STA_STAFF_BASIC_SALARY_TRG_AU
    AFTER UPDATE
    ON STA_STAFF_BASIC_SALARY
    FOR EACH ROW
BEGIN
    INSERT INTO STA_STAFF_BASIC_SALARY_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                         STAFF_ID, BASIC_SALARY, CATERING_SUBSIDIES, TRANSPORTATION_SUBSIDIES,
                                         DEVICES_SUBSIDIES, POSITION_SUBSIDIES,
                                         OTHER_SUBSIDIES, BONUS, CREATED_AT, CREATED_BY, UPDATED_AT,
                                         UPDATED_BY)
    VALUES (NULL, 'AU', NOW(),
            NEW.STAFF_ID, NEW.BASIC_SALARY, NEW.CATERING_SUBSIDIES, NEW.TRANSPORTATION_SUBSIDIES, NEW.DEVICES_SUBSIDIES,
            NEW.POSITION_SUBSIDIES,
            NEW.OTHER_SUBSIDIES, NEW.BONUS, NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT,
            NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STA_STAFF_BASIC_SALARY_TRG_BD
    BEFORE DELETE
    ON STA_STAFF_BASIC_SALARY
    FOR EACH ROW
BEGIN
    INSERT INTO STA_STAFF_BASIC_SALARY_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                         STAFF_ID, BASIC_SALARY, CATERING_SUBSIDIES, TRANSPORTATION_SUBSIDIES,
                                         DEVICES_SUBSIDIES, POSITION_SUBSIDIES,
                                         OTHER_SUBSIDIES, BONUS, CREATED_AT, CREATED_BY, UPDATED_AT,
                                         UPDATED_BY)
    VALUES (NULL, 'BD', NOW(),
            OLD.STAFF_ID, OLD.BASIC_SALARY, OLD.CATERING_SUBSIDIES, OLD.TRANSPORTATION_SUBSIDIES, OLD.DEVICES_SUBSIDIES,
            OLD.POSITION_SUBSIDIES,
            OLD.OTHER_SUBSIDIES, OLD.BONUS, OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT,
            OLD.UPDATED_BY);
END ##
DELIMITER ;