CREATE TABLE STA_STAFF_REGISTRATION
(
    STAFF_ID                VARCHAR(16) NOT NULL,
    RESUME_CM_DOCUMENT_ID   BIGINT      NOT NULL, /*简历文档*/
    MER_CM_DOCUMENT_ID      BIGINT      NOT NULL, /*体检报告*/
    AC_CM_DOCUMENT_ID       BIGINT      NOT NULL, /*学历证书*/
    DIPLOMA_CM_DOCUMENT_ID  BIGINT      NOT NULL, /*学位证书*/
    CONTRACT_CM_DOCUMENT_ID BIGINT      NOT NULL, /*劳动合同*/
    EDUCATION               CHAR(1)     NOT NULL, /*学历*/
    RECRUITMENT_METHOD      VARCHAR(16) NOT NULL, /*招聘方式*/
    WRITTEN_EXAM_SCORE      INT         NOT NULL,
    INTERVIEW_TYPE          VARCHAR(16) NOT NULL,
    INTERVIEW_SCORE         INT         NOT NULL,
    INTERVIEWED_AT          DATE        NOT NULL,
    INTERVIEWED_BY          VARCHAR(16) NOT NULL,
    OFFER_SENT_AT           DATE        NOT NULL,
    OFFER_CM_DOCUMENT_ID    BIGINT      NOT NULL,
    REQUIRED_ENTRY_TIME     DATE        NOT NULL,
    ACTUAL_ENTRY_TIME       DATE        NOT NULL,
    PROBATION_UNTIL_DATE    DATE        NOT NULL,
    GRADUATED_FROM_UNI      VARCHAR(64),
    MAJOR                   VARCHAR(6),
    GRADUATED_DATE          DATE,
    CREATED_AT              DATETIME    NOT NULL,
    CREATED_BY              VARCHAR(32) NOT NULL,
    UPDATED_AT              DATETIME    NOT NULL,
    UPDATED_BY              VARCHAR(32) NOT NULL
);