CREATE TABLE STA_STAFF
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    STAFF_NO       VARCHAR(16) NOT NULL UNIQUE,
    DEPARTMENT_ID  INT         NOT NULL,
    POSITION_ID    INT         NOT NULL,
    POSITION_LEVEL VARCHAR(2)  NOT NULL,
    PROJECT_ID     INT         NOT NULL,
    ENTRY_NO       INT         NOT NULL,
    JOINED_DATE    DATE,
    RESIGN_DATE    DATE,
    NAME           VARCHAR(64) NOT NULL,
    NICKNAME       VARCHAR(64) UNIQUE,
    GENDER         CHAR(1)     NOT NULL,
    DOB            DATE,
    AGE            INT,
    PHONE_NO       VARCHAR(13),
    EMAIL_ADDRESS  VARCHAR(128),
    QQ             VARCHAR(15),
    WECHAT         VARCHAR(64),
    PROFILE        VARCHAR(100),
    STATUS         VARCHAR(16) NOT NULL,
    PORTRAIT       MEDIUMBLOB,
    PORTRAIT_EXT   VARCHAR(6),
    CREATED_AT     DATETIME    NOT NULL,
    CREATED_BY     VARCHAR(32) NOT NULL,
    UPDATED_AT     DATETIME    NOT NULL,
    UPDATED_BY     VARCHAR(32) NOT NULL
);

CREATE TABLE STA_STAFF_H
(
    AUDIT_ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUDIT_TYPE     CHAR(2),
    AUDIT_TIME     DATETIME,
    ID             BIGINT,
    STAFF_NO       VARCHAR(16),
    DEPARTMENT_ID  INT,
    POSITION_ID    INT,
    POSITION_LEVEL VARCHAR(2),
    PROJECT_ID     INT,
    ENTRY_NO       INT,
    JOINED_DATE    DATE,
    RESIGN_DATE    DATE,
    NAME           VARCHAR(64),
    NICKNAME       VARCHAR(64),
    GENDER         CHAR(1),
    DOB            DATE,
    AGE            INT,
    PHONE_NO       VARCHAR(13),
    EMAIL_ADDRESS  VARCHAR(128),
    QQ             VARCHAR(15),
    WECHAT         VARCHAR(64),
    PROFILE        VARCHAR(100),
    STATUS         VARCHAR(16),
    PORTRAIT       MEDIUMBLOB,
    PORTRAIT_EXT   VARCHAR(6),
    CREATED_AT     DATETIME,
    CREATED_BY     VARCHAR(32),
    UPDATED_AT     DATETIME,
    UPDATED_BY     VARCHAR(32)
);

DELIMITER ##
CREATE TRIGGER STA_STAFF_TRG_AI
    AFTER INSERT
    ON STA_STAFF
    FOR EACH ROW
BEGIN
    INSERT INTO STA_STAFF_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                            ID, STAFF_NO, DEPARTMENT_ID, POSITION_ID, POSITION_LEVEL, PROJECT_ID,
                            ENTRY_NO, JOINED_DATE, RESIGN_DATE, NAME, NICKNAME,
                            GENDER, DOB, AGE, PHONE_NO, EMAIL_ADDRESS,
                            QQ, WECHAT, PROFILE, STATUS, PORTRAIT,
                            PORTRAIT_EXT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'AI', NOW(),
            NEW.ID, NEW.STAFF_NO, NEW.DEPARTMENT_ID, NEW.POSITION_ID, NEW.POSITION_LEVEL, NEW.PROJECT_ID,
            NEW.ENTRY_NO, NEW.JOINED_DATE, NEW.RESIGN_DATE, NEW.NAME, NEW.NICKNAME,
            NEW.GENDER, NEW.DOB, NEW.AGE, NEW.PHONE_NO, NEW.EMAIL_ADDRESS,
            NEW.QQ, NEW.WECHAT, NEW.PROFILE, NEW.STATUS, NEW.PORTRAIT,
            NEW.PORTRAIT_EXT, NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT, NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STA_STAFF_TRG_BU
    BEFORE UPDATE
    ON STA_STAFF
    FOR EACH ROW
BEGIN
    INSERT INTO STA_STAFF_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                            ID, STAFF_NO, DEPARTMENT_ID, POSITION_ID, POSITION_LEVEL, PROJECT_ID,
                            ENTRY_NO, JOINED_DATE, RESIGN_DATE, NAME, NICKNAME,
                            GENDER, DOB, AGE, PHONE_NO, EMAIL_ADDRESS,
                            QQ, WECHAT, PROFILE, STATUS, PORTRAIT,
                            PORTRAIT_EXT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'BU', NOW(),
            OLD.ID, OLD.STAFF_NO, OLD.DEPARTMENT_ID, OLD.POSITION_ID, OLD.POSITION_LEVEL, OLD.PROJECT_ID,
            OLD.ENTRY_NO, OLD.JOINED_DATE, OLD.RESIGN_DATE, OLD.NAME, OLD.NICKNAME,
            OLD.GENDER, OLD.DOB, OLD.AGE, OLD.PHONE_NO, OLD.EMAIL_ADDRESS,
            OLD.QQ, OLD.WECHAT, OLD.PROFILE, OLD.STATUS, OLD.PORTRAIT,
            OLD.PORTRAIT_EXT, OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT, OLD.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STA_STAFF_TRG_AU
    AFTER UPDATE
    ON STA_STAFF
    FOR EACH ROW
BEGIN
    INSERT INTO STA_STAFF_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                            ID, STAFF_NO, DEPARTMENT_ID, POSITION_ID, POSITION_LEVEL, PROJECT_ID,
                            ENTRY_NO, JOINED_DATE, RESIGN_DATE, NAME, NICKNAME,
                            GENDER, DOB, AGE, PHONE_NO, EMAIL_ADDRESS,
                            QQ, WECHAT, PROFILE, STATUS, PORTRAIT,
                            PORTRAIT_EXT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'AU', NOW(),
            NEW.ID, NEW.STAFF_NO, NEW.DEPARTMENT_ID, NEW.POSITION_ID, NEW.POSITION_LEVEL, NEW.PROJECT_ID,
            NEW.ENTRY_NO, NEW.JOINED_DATE, NEW.RESIGN_DATE, NEW.NAME, NEW.NICKNAME,
            NEW.GENDER, NEW.DOB, NEW.AGE, NEW.PHONE_NO, NEW.EMAIL_ADDRESS,
            NEW.QQ, NEW.WECHAT, NEW.PROFILE, NEW.STATUS, NEW.PORTRAIT,
            NEW.PORTRAIT_EXT, NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT, NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STA_STAFF_TRG_BD
    BEFORE DELETE
    ON STA_STAFF
    FOR EACH ROW
BEGIN
    INSERT INTO STA_STAFF_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                            ID, STAFF_NO, DEPARTMENT_ID, POSITION_ID, POSITION_LEVEL, PROJECT_ID,
                            ENTRY_NO, JOINED_DATE, RESIGN_DATE, NAME, NICKNAME,
                            GENDER, DOB, AGE, PHONE_NO, EMAIL_ADDRESS,
                            QQ, WECHAT, PROFILE, STATUS, PORTRAIT,
                            PORTRAIT_EXT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'BD', NOW(),
            OLD.ID, OLD.STAFF_NO, OLD.DEPARTMENT_ID, OLD.POSITION_ID, OLD.POSITION_LEVEL, OLD.PROJECT_ID,
            OLD.ENTRY_NO, OLD.JOINED_DATE, OLD.RESIGN_DATE, OLD.NAME, OLD.NICKNAME,
            OLD.GENDER, OLD.DOB, OLD.AGE, OLD.PHONE_NO, OLD.EMAIL_ADDRESS,
            OLD.QQ, OLD.WECHAT, OLD.PROFILE, OLD.STATUS, OLD.PORTRAIT,
            OLD.PORTRAIT_EXT, OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT, OLD.UPDATED_BY);
END ##
DELIMITER ;