CREATE TABLE STU_STUDENT_COURSE
(
    STU_COURSE_ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    STU_NO          VARCHAR(16),
    MAJOR_CODE      VARCHAR(6)  NOT NULL,
    COURSE_CODE     VARCHAR(16)  NOT NULL,
    CLASS_NO        VARCHAR(6)  NOT NULL,
    GRADE           INT,
    SEMESTER        INT         NOT NULL,
    COURSE_SUBJECT  VARCHAR(6),
    CREDIT          DOUBLE      NOT NULL,
    SCORING_TYPE    CHAR(1),
    WEIGHT          INT         NOT NULL,
    COURSE_COLLEGE  VARCHAR(6),
    TEACHER         VARCHAR(16) NOT NULL,
    SCHEDULE        VARCHAR(32) NOT NULL,
    IS_CORE         CHAR(1),
    IS_COMPULSORY   CHAR(1),
    IS_OPTIONAL     CHAR(1),
    IS_GENERAL      CHAR(1),
    IS_PROFESSIONAL CHAR(1),
    IS_FIRST        CHAR(1),
    IS_RELEARNING   CHAR(1),
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_BY      VARCHAR(32) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_BY      VARCHAR(32) NOT NULL

);