CREATE TABLE STU_STUDENT_DEMOGRAPHIC_PF
(
    USER_ID            BIGINT,
    STU_NO             VARCHAR(16),
    NAME               VARCHAR(24) NOT NULL,
    DOB                DATE,
    AGE                INT,
    GENDER             CHAR(1),
    NATIONALITY        VARCHAR(6),
    ID_CARD_NO         VARCHAR(32) NOT NULL,
    ID_ADDRESS          VARCHAR(500),
    DOMICILE           VARCHAR(16),
    DOMICILE_TYPE      CHAR(1)     NOT NULL,
    NATIVE_PLACE       VARCHAR(16),
    NATION             VARCHAR(6),
    RELIGION           VARCHAR(6),
    IS_ETHNIC_MINORITY CHAR(1),
    MARITAL_STATUS     CHAR(1),
    CREATED_AT         DATETIME    NOT NULL,
    CREATED_BY         VARCHAR(32) NOT NULL,
    UPDATED_AT         DATETIME    NOT NULL,
    UPDATED_BY         VARCHAR(32) NOT NULL
);

ALTER TABLE STU_STUDENT_DEMOGRAPHIC_PF
    ADD CONSTRAINT DG_STU_NO_FK FOREIGN KEY (STU_NO) REFERENCES STU_STUDENT (STU_NO);

CREATE TABLE STU_STUDENT_DEMOGRAPHIC_PF_H
(
    AUDIT_ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUDIT_TYPE         CHAR(2),
    AUDIT_TIME         DATETIME,
    USER_ID            BIGINT,
    STU_NO             VARCHAR(16),
    NAME               VARCHAR(24),
    DOB                DATE,
    AGE                INT,
    GENDER             CHAR(1),
    NATIONALITY        VARCHAR(6),
    ID_CARD_NO         VARCHAR(32),
    ID_ADDRESS       VARCHAR(500),
    DOMICILE           VARCHAR(16),
    DOMICILE_TYPE      CHAR(1),
    NATIVE_PLACE       VARCHAR(16),
    NATION             VARCHAR(6),
    RELIGION           VARCHAR(6),
    IS_ETHNIC_MINORITY CHAR(1),
    MARITAL_STATUS     CHAR(1),
    CREATED_AT         DATETIME,
    CREATED_BY         VARCHAR(32),
    UPDATED_AT         DATETIME,
    UPDATED_BY         VARCHAR(32)
);

DELIMITER ##
CREATE TRIGGER STU_STUDENT_DEMOGRAPHIC_PF_TRG_AI
    AFTER INSERT
    ON STU_STUDENT_DEMOGRAPHIC_PF
    FOR EACH ROW
BEGIN
    INSERT INTO STU_STUDENT_DEMOGRAPHIC_PF_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                             USER_ID, STU_NO, NAME, DOB, AGE, GENDER,
                                             NATIONALITY, ID_CARD_NO, ID_ADDRESS, DOMICILE, DOMICILE_TYPE,
                                             NATIVE_PLACE, NATION, RELIGION, IS_ETHNIC_MINORITY, MARITAL_STATUS,
                                             CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'AI', NOW(),
            NEW.USER_ID, NEW.STU_NO, NEW.NAME, NEW.DOB, NEW.AGE, NEW.GENDER,
            NEW.NATIONALITY, NEW.ID_CARD_NO, NEW.ID_ADDRESS, NEW.DOMICILE, NEW.DOMICILE_TYPE,
            NEW.NATIVE_PLACE, NEW.NATION, NEW.RELIGION, NEW.IS_ETHNIC_MINORITY, NEW.MARITAL_STATUS,
            NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT, NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STU_STUDENT_DEMOGRAPHIC_PF_TRG_BU
    BEFORE UPDATE
    ON STU_STUDENT_DEMOGRAPHIC_PF
    FOR EACH ROW
BEGIN
    INSERT INTO STU_STUDENT_DEMOGRAPHIC_PF_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                             USER_ID, STU_NO, NAME, DOB, AGE, GENDER,
                                             NATIONALITY, ID_CARD_NO, ID_ADDRESS, DOMICILE, DOMICILE_TYPE,
                                             NATIVE_PLACE, NATION, RELIGION, IS_ETHNIC_MINORITY, MARITAL_STATUS,
                                             CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'BU', NOW(),
            OLD.USER_ID, OLD.STU_NO, OLD.NAME, OLD.DOB, OLD.AGE, OLD.GENDER,
            OLD.NATIONALITY, OLD.ID_CARD_NO, OLD.ID_ADDRESS, OLD.DOMICILE, OLD.DOMICILE_TYPE,
            OLD.NATIVE_PLACE, OLD.NATION, OLD.RELIGION, OLD.IS_ETHNIC_MINORITY, OLD.MARITAL_STATUS,
            OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT, OLD.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STU_STUDENT_DEMOGRAPHIC_PF_TRG_AU
    AFTER UPDATE
    ON STU_STUDENT_DEMOGRAPHIC_PF
    FOR EACH ROW
BEGIN
    INSERT INTO STU_STUDENT_DEMOGRAPHIC_PF_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                             USER_ID, STU_NO, NAME, DOB, AGE, GENDER,
                                             NATIONALITY, ID_CARD_NO, ID_ADDRESS, DOMICILE, DOMICILE_TYPE,
                                             NATIVE_PLACE, NATION, RELIGION, IS_ETHNIC_MINORITY, MARITAL_STATUS,
                                             CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'AU', NOW(),
            NEW.USER_ID, NEW.STU_NO, NEW.NAME, NEW.DOB, NEW.AGE, NEW.GENDER,
            NEW.NATIONALITY, NEW.ID_CARD_NO, NEW.ID_ADDRESS, NEW.DOMICILE, NEW.DOMICILE_TYPE,
            NEW.NATIVE_PLACE, NEW.NATION, NEW.RELIGION, NEW.IS_ETHNIC_MINORITY, NEW.MARITAL_STATUS,
            NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT, NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STU_STUDENT_DEMOGRAPHIC_PF_TRG_BD
    BEFORE DELETE
    ON STU_STUDENT_DEMOGRAPHIC_PF
    FOR EACH ROW
BEGIN
    INSERT INTO STU_STUDENT_DEMOGRAPHIC_PF_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                             USER_ID, STU_NO, NAME, DOB, AGE, GENDER,
                                             NATIONALITY, ID_CARD_NO, ID_ADDRESS, DOMICILE, DOMICILE_TYPE,
                                             NATIVE_PLACE, NATION, RELIGION, IS_ETHNIC_MINORITY, MARITAL_STATUS,
                                             CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'BD', NOW(),
            OLD.USER_ID, OLD.STU_NO, OLD.NAME, OLD.DOB, OLD.AGE, OLD.GENDER,
            OLD.NATIONALITY, OLD.ID_CARD_NO, OLD.ID_ADDRESS, OLD.DOMICILE, OLD.DOMICILE_TYPE,
            OLD.NATIVE_PLACE, OLD.NATION, OLD.RELIGION, OLD.IS_ETHNIC_MINORITY, OLD.MARITAL_STATUS,
            OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT, OLD.UPDATED_BY);
END ##
DELIMITER ;
