CREATE TABLE STU_TRANSCRIPT
(
    STU_TRANSCRIPT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    STU_COURSE_ID     BIGINT,
    STU_NO            VARCHAR(16),
    COURSE_CODE       VARCHAR(16)  NOT NULL,
    SCORE             DOUBLE,
    RATE              CHAR(1),
    COURSE_CREDIT     DOUBLE      NOT NULL,
    EARNED_CREDIT     DOUBLE      NOT NULL,
    GRADE_POINT       DOUBLE      NOT NULL,
    IS_PASSED         CHAR(1),
    IS_MADE_UP        CHAR(1),
    MAKE_UP_SCORE     DOUBLE,
    MAKE_UP_RATE      CHAR(1),
    CREATED_AT        DATETIME    NOT NULL,
    CREATED_BY        VARCHAR(32) NOT NULL,
    UPDATED_AT        DATETIME    NOT NULL,
    UPDATED_BY        VARCHAR(32) NOT NULL
);

ALTER TABLE STU_TRANSCRIPT ADD CONSTRAINT STU_TRANSCRIPT_FK FOREIGN KEY (STU_COURSE_ID) REFERENCES STU_STUDENT_COURSE (STU_COURSE_ID);