CREATE TABLE STU_STUDENT_STATUS
(
    STU_NO                      VARCHAR(16),
    PRIMARY_SCHOOL              VARCHAR(500),
    PRI_CLASS_TEACHER           VARCHAR(32),
    PRI_FROM                    DATE,
    PRI_END                     DATE,
    MID_CLASS_TEACHER           VARCHAR(32),
    MIDDLE_SCHOOL               VARCHAR(500),
    MID_FROM                    DATE,
    MID_END                     DATE,
    HIGH_SCHOOL                 VARCHAR(500),
    HIGH_CLASS_TEACHER          VARCHAR(32),
    HIGH_FROM                   DATE,
    HIGH_END                    DATE,
    IS_REGISTERED               CHAR(1)     NOT NULL,
    REGISTRATION_DATE           DATE,
    IS_SUSPENDED                CHAR(1),
    SUSPEND_FROM                DATE,
    SUSPEND_END                 DATE,
    IS_DROPPED_OUT              CHAR(1),
    DROPPED_OUT_DATE            DATE,
    IS_WARNED                   CHAR(1),
    IS_SERIOUSLY_WARNED         CHAR(1),
    IS_RECORDED_DEMERIT         CHAR(1),
    IS_RECORDED_SERIOUS_DEMERIT CHAR(1),
    IS_ON_PROBATION             CHAR(1),
    IS_EXPELLED                 CHAR(1),
    IS_RECOMMENDED_MASTER       CHAR(1),
    CREATED_AT                  DATETIME    NOT NULL,
    CREATED_BY                  VARCHAR(24) NOT NULL,
    UPDATED_AT                  DATETIME    NOT NULL,
    UPDATED_BY                  VARCHAR(24) NOT NULL
);

ALTER TABLE STU_STUDENT_STATUS ADD CONSTRAINT STATUS_STU_NO_FK FOREIGN KEY (STU_NO) REFERENCES STU_STUDENT (STU_NO);

CREATE TABLE STU_STUDENT_STATUS_H
(
    AUDIT_ID                    BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUDIT_TYPE                  CHAR(2),
    AUDIT_TIME                  DATETIME,
    STU_NO                      VARCHAR(16),
    PRIMARY_SCHOOL              VARCHAR(500),
    PRI_CLASS_TEACHER           VARCHAR(32),
    PRI_FROM                    DATE,
    PRI_END                     DATE,
    MID_CLASS_TEACHER           VARCHAR(32),
    MIDDLE_SCHOOL               VARCHAR(500),
    MID_FROM                    DATE,
    MID_END                     DATE,
    HIGH_SCHOOL                 VARCHAR(500),
    HIGH_CLASS_TEACHER          VARCHAR(32),
    HIGH_FROM                   DATE,
    HIGH_END                    DATE,
    IS_REGISTERED               CHAR(1),
    REGISTRATION_DATE           DATE,
    IS_SUSPENDED                CHAR(1),
    SUSPEND_FROM                DATE,
    SUSPEND_END                 DATE,
    IS_DROPPED_OUT              CHAR(1),
    DROPPED_OUT_DATE            DATE,
    IS_WARNED                   CHAR(1),
    IS_SERIOUSLY_WARNED         CHAR(1),
    IS_RECORDED_DEMERIT         CHAR(1),
    IS_RECORDED_SERIOUS_DEMERIT CHAR(1),
    IS_ON_PROBATION             CHAR(1),
    IS_EXPELLED                 CHAR(1),
    IS_RECOMMENDED_MASTER       CHAR(1),
    CREATED_AT                  DATETIME,
    CREATED_BY                  VARCHAR(24),
    UPDATED_AT                  DATETIME,
    UPDATED_BY                  VARCHAR(24)
);


DELIMITER ##
CREATE TRIGGER STU_STUDENT_STATUS_TRG_AI
    AFTER INSERT
    ON STU_STUDENT_STATUS
    FOR EACH ROW
BEGIN
    INSERT INTO STU_STUDENT_STATUS_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                     STU_NO, PRIMARY_SCHOOL, PRI_CLASS_TEACHER, PRI_FROM, PRI_END, MID_CLASS_TEACHER,
                                     MIDDLE_SCHOOL, MID_FROM, MID_END, HIGH_SCHOOL, HIGH_CLASS_TEACHER,
                                     HIGH_FROM, HIGH_END, IS_REGISTERED, REGISTRATION_DATE, IS_SUSPENDED,
                                     SUSPEND_FROM, SUSPEND_END, IS_DROPPED_OUT, DROPPED_OUT_DATE, IS_WARNED,
                                     IS_SERIOUSLY_WARNED, IS_RECORDED_DEMERIT, IS_RECORDED_SERIOUS_DEMERIT,
                                     IS_ON_PROBATION, IS_EXPELLED,
                                     IS_RECOMMENDED_MASTER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'AI', NOW(),
            NEW.STU_NO, NEW.PRIMARY_SCHOOL, NEW.PRI_CLASS_TEACHER, NEW.PRI_FROM, NEW.PRI_END, NEW.MID_CLASS_TEACHER,
            NEW.MIDDLE_SCHOOL, NEW.MID_FROM, NEW.MID_END, NEW.HIGH_SCHOOL, NEW.HIGH_CLASS_TEACHER,
            NEW.HIGH_FROM, NEW.HIGH_END, NEW.IS_REGISTERED, NEW.REGISTRATION_DATE, NEW.IS_SUSPENDED,
            NEW.SUSPEND_FROM, NEW.SUSPEND_END, NEW.IS_DROPPED_OUT, NEW.DROPPED_OUT_DATE, NEW.IS_WARNED,
            NEW.IS_SERIOUSLY_WARNED, NEW.IS_RECORDED_DEMERIT, NEW.IS_RECORDED_SERIOUS_DEMERIT, NEW.IS_ON_PROBATION,
            NEW.IS_EXPELLED,
            NEW.IS_RECOMMENDED_MASTER, NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT, NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STU_STUDENT_STATUS_TRG_BU
    BEFORE UPDATE
    ON STU_STUDENT_STATUS
    FOR EACH ROW
BEGIN
    INSERT INTO STU_STUDENT_STATUS_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                     STU_NO, PRIMARY_SCHOOL, PRI_CLASS_TEACHER, PRI_FROM, PRI_END, MID_CLASS_TEACHER,
                                     MIDDLE_SCHOOL, MID_FROM, MID_END, HIGH_SCHOOL, HIGH_CLASS_TEACHER,
                                     HIGH_FROM, HIGH_END, IS_REGISTERED, REGISTRATION_DATE, IS_SUSPENDED,
                                     SUSPEND_FROM, SUSPEND_END, IS_DROPPED_OUT, DROPPED_OUT_DATE, IS_WARNED,
                                     IS_SERIOUSLY_WARNED, IS_RECORDED_DEMERIT, IS_RECORDED_SERIOUS_DEMERIT,
                                     IS_ON_PROBATION, IS_EXPELLED,
                                     IS_RECOMMENDED_MASTER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'BU', NOW(),
            OLD.STU_NO, OLD.PRIMARY_SCHOOL, OLD.PRI_CLASS_TEACHER, OLD.PRI_FROM, OLD.PRI_END, OLD.MID_CLASS_TEACHER,
            OLD.MIDDLE_SCHOOL, OLD.MID_FROM, OLD.MID_END, OLD.HIGH_SCHOOL, OLD.HIGH_CLASS_TEACHER,
            OLD.HIGH_FROM, OLD.HIGH_END, OLD.IS_REGISTERED, OLD.REGISTRATION_DATE, OLD.IS_SUSPENDED,
            OLD.SUSPEND_FROM, OLD.SUSPEND_END, OLD.IS_DROPPED_OUT, OLD.DROPPED_OUT_DATE, OLD.IS_WARNED,
            OLD.IS_SERIOUSLY_WARNED, OLD.IS_RECORDED_DEMERIT, OLD.IS_RECORDED_SERIOUS_DEMERIT, OLD.IS_ON_PROBATION,
            OLD.IS_EXPELLED,
            OLD.IS_RECOMMENDED_MASTER, OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT, OLD.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STU_STUDENT_STATUS_TRG_AU
    AFTER UPDATE
    ON STU_STUDENT_STATUS
    FOR EACH ROW
BEGIN
    INSERT INTO STU_STUDENT_STATUS_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                     STU_NO, PRIMARY_SCHOOL, PRI_CLASS_TEACHER, PRI_FROM, PRI_END, MID_CLASS_TEACHER,
                                     MIDDLE_SCHOOL, MID_FROM, MID_END, HIGH_SCHOOL, HIGH_CLASS_TEACHER,
                                     HIGH_FROM, HIGH_END, IS_REGISTERED, REGISTRATION_DATE, IS_SUSPENDED,
                                     SUSPEND_FROM, SUSPEND_END, IS_DROPPED_OUT, DROPPED_OUT_DATE, IS_WARNED,
                                     IS_SERIOUSLY_WARNED, IS_RECORDED_DEMERIT, IS_RECORDED_SERIOUS_DEMERIT,
                                     IS_ON_PROBATION, IS_EXPELLED,
                                     IS_RECOMMENDED_MASTER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'AU', NOW(),
            NEW.STU_NO, NEW.PRIMARY_SCHOOL, NEW.PRI_CLASS_TEACHER, NEW.PRI_FROM, NEW.PRI_END, NEW.MID_CLASS_TEACHER,
            NEW.MIDDLE_SCHOOL, NEW.MID_FROM, NEW.MID_END, NEW.HIGH_SCHOOL, NEW.HIGH_CLASS_TEACHER,
            NEW.HIGH_FROM, NEW.HIGH_END, NEW.IS_REGISTERED, NEW.REGISTRATION_DATE, NEW.IS_SUSPENDED,
            NEW.SUSPEND_FROM, NEW.SUSPEND_END, NEW.IS_DROPPED_OUT, NEW.DROPPED_OUT_DATE, NEW.IS_WARNED,
            NEW.IS_SERIOUSLY_WARNED, NEW.IS_RECORDED_DEMERIT, NEW.IS_RECORDED_SERIOUS_DEMERIT, NEW.IS_ON_PROBATION,
            NEW.IS_EXPELLED,
            NEW.IS_RECOMMENDED_MASTER, NEW.CREATED_AT, NEW.CREATED_BY, NEW.UPDATED_AT, NEW.UPDATED_BY);
END ##
DELIMITER ;

DELIMITER ##
CREATE TRIGGER STU_STUDENT_STATUS_TRG_BD
    BEFORE DELETE
    ON STU_STUDENT_STATUS
    FOR EACH ROW
BEGIN
    INSERT INTO STU_STUDENT_STATUS_H(AUDIT_ID, AUDIT_TYPE, AUDIT_TIME,
                                     STU_NO, PRIMARY_SCHOOL, PRI_CLASS_TEACHER, PRI_FROM, PRI_END, MID_CLASS_TEACHER,
                                     MIDDLE_SCHOOL, MID_FROM, MID_END, HIGH_SCHOOL, HIGH_CLASS_TEACHER,
                                     HIGH_FROM, HIGH_END, IS_REGISTERED, REGISTRATION_DATE, IS_SUSPENDED,
                                     SUSPEND_FROM, SUSPEND_END, IS_DROPPED_OUT, DROPPED_OUT_DATE, IS_WARNED,
                                     IS_SERIOUSLY_WARNED, IS_RECORDED_DEMERIT, IS_RECORDED_SERIOUS_DEMERIT,
                                     IS_ON_PROBATION, IS_EXPELLED,
                                     IS_RECOMMENDED_MASTER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUES (NULL, 'BD', NOW(),
            OLD.STU_NO, OLD.PRIMARY_SCHOOL, OLD.PRI_CLASS_TEACHER, OLD.PRI_FROM, OLD.PRI_END, OLD.MID_CLASS_TEACHER,
            OLD.MIDDLE_SCHOOL, OLD.MID_FROM, OLD.MID_END, OLD.HIGH_SCHOOL, OLD.HIGH_CLASS_TEACHER,
            OLD.HIGH_FROM, OLD.HIGH_END, OLD.IS_REGISTERED, OLD.REGISTRATION_DATE, OLD.IS_SUSPENDED,
            OLD.SUSPEND_FROM, OLD.SUSPEND_END, OLD.IS_DROPPED_OUT, OLD.DROPPED_OUT_DATE, OLD.IS_WARNED,
            OLD.IS_SERIOUSLY_WARNED, OLD.IS_RECORDED_DEMERIT, OLD.IS_RECORDED_SERIOUS_DEMERIT, OLD.IS_ON_PROBATION,
            OLD.IS_EXPELLED,
            OLD.IS_RECOMMENDED_MASTER, OLD.CREATED_AT, OLD.CREATED_BY, OLD.UPDATED_AT, OLD.UPDATED_BY);
END ##
DELIMITER ;